name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    
  workflow_dispatch:
  
jobs:

  # esse woekflow contém um único job chamado "build"
  CI:
  
  # tipo de runner
    runs-on: ubuntu-latest
    
    # sequencia de tarefas
    steps:
    
      - uses: actions/checkout@v2
      
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.6.0
        with:
          node-version: 16.13.2
          
      - name: Instalação do mocha
        run: |
          cd src;
          npm install -g mocha
          npm install
          
      - name: execução do teste
        run: mocha src/test/convert.js
